# Generated by Django 3.0.8 on 2020-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
