# Generated by Django 3.0.8 on 2020-10-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0002_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dum', models.DateField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('alergia', models.TextField(blank=True, null=True)),
                ('cafeina', models.BooleanField(blank=True, null=True)),
                ('asma', models.BooleanField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_exame', models.CharField(blank=True, choices=[('Cintilografia Miocárdica', 'Cintilografia Miocárdica'), ('Pesquisa de Viabilidade', 'Pesquisa de Viabilidade')], max_length=255, null=True)),
                ('cintilografia_adicional', models.CharField(blank=True, choices=[('Protocolo de 1 dia', 'Protocolo de 1 dia'), ('Protocolo de 2 dias', 'Protocolo de 2 dias')], max_length=255, null=True)),
                ('viabilidade_adicional', models.CharField(blank=True, choices=[('Rep/Redist T', 'Rep/Redist T'), ('Est/Redist/Redist T', 'Est/Redist/Redist T')], max_length=255, null=True)),
                ('motivo_exame', models.TextField(blank=True, null=True)),
                ('hda', models.TextField(blank=True, null=True)),
                ('hpp', models.TextField(blank=True, null=True)),
                ('exames_previos', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anamneses.Medico')),
                ('medico_assistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico_assistente', to='anamneses.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anamneses.Paciente')),
            ],
        ),
    ]
