# Generated by Django 3.0.8 on 2020-11-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0003_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='motivo_exame',
            field=models.CharField(blank=True, choices=[('dor_toráxica', 'Dor toráxica'), ('pós-SCA', 'pós-SCA'), ('Alteração exame', 'Alteração exame'), ('Equiv. anginoso', 'Equiv. anginoso'), ('pós-CRVM', 'pós-CRVM'), ('Lesão coronária', 'Lesão coronária'), ('Arritmia', 'Arritmia'), ('pós-PTCA', 'pós-PTCA'), ('ICC', 'ICC'), ('Síncope', 'Síncope')], max_length=255, null=True),
        ),
    ]
