# Generated by Django 3.0.8 on 2020-11-07 15:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0005_auto_20201102_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='hpp',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hpp_comorbidades',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('avc', 'AVC'), ('irc', 'IRC'), ('aao', 'AAo'), ('doenca_vascular', 'Doença vascular')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hpp_dac',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('iam', 'IAM'), ('crvm', 'CRVM'), ('ptca', 'PTCA'), ('cat_alterado', 'CAT alterado')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hpp_risco',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('has', 'HAS'), ('obesidade', 'Obesidade'), ('dm', 'D.M.'), ('dislipidemia', 'Dislipidemia'), ('tabagismo', 'Tabagismo'), ('hf', 'HF'), ('ex_tabagismo', 'Ex-tabagismo'), ('menopausa', 'Menopausa')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hda',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('assintomatico', 'Assintomático'), ('cansaco', 'Cansaço'), ('sincope', 'Síncope'), ('dor_toracica_tipica', 'Dor torácica típica'), ('dor torarica_atipica', 'Dor torácica atípica'), ('dispneia_esforcos', 'Dispnéia aos esforços'), ('dispneia_repouso', 'Dispnéia de repouso'), ('palpitacoes', 'Palpitações')], max_length=117, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anamneses.Medico'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='motivo_exame',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dor_toracica', 'Dor torácica'), ('pos_sca', 'pós-SCA'), ('alteracao_exame', 'Alteração exame'), ('equiv_anginoso', 'Equiv. anginoso'), ('pos_crvm', 'pós-CRVM'), ('lesao_coronaria', 'Lesão coronária'), ('arritmia', 'Arritmia'), ('pos_ptca', 'pós-PTCA'), ('icc', 'ICC'), ('sincope', 'Síncope'), ('risco_cirurgico', 'Risco cirúrgico')], max_length=122, null=True),
        ),
    ]
