# Generated by Django 3.0.8 on 2020-11-07 20:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0006_auto_20201107_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='exames_previos',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_cat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_cm',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('isquemia', 'Isquemia'), ('fibrose', 'Fibrose'), ('isq_fib', 'Isq/fib'), ('gated_alt', 'Gated alt.')], max_length=41, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_eco',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_fe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('alt_segmentar', 'Alt. segmentar'), ('disf_sistolica', 'Disf. sistólica'), ('disf_diastolica', 'Disf. diastólica')], max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_mets',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ecg', 'ECG'), ('dor', 'Dor'), ('arritmia', 'Arritmia'), ('baixo_pa', '&#8595 PA')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_tce',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('da', 'DA'), ('cx', 'CX'), ('cd', 'CD'), ('saf', 'Saf'), ('mam', 'Mam')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='exames_previos_te',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True),
        ),
    ]
