# Generated by Django 3.0.8 on 2020-11-07 20:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0007_auto_20201107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='medicamentos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bloq_calcio', 'Bloq. Cálcio'), ('aas', 'AAS'), ('nitrato', 'Nitrato'), ('beta_bloqueador', '&#946-bloqueador'), ('estatina', 'Estatina'), ('diuretico', 'Diurético'), ('bra', 'BRA'), ('ieca', 'IECA'), ('clopido_rel', 'Clopido.rel')], max_length=79, null=True),
        ),
    ]
