# Generated by Django 3.0.8 on 2020-11-07 21:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0008_auto_20201107_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_cat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True, verbose_name='CAT'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_cm',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('isquemia', 'Isquemia'), ('fibrose', 'Fibrose'), ('isq_fib', 'Isq/fib'), ('gated_alt', 'Gated alt.')], max_length=41, null=True, verbose_name='CM'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_eco',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True, verbose_name='ECO'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_fe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('alt_segmentar', 'Alt. segmentar'), ('disf_sistolica', 'Disf. sistólica'), ('disf_diastolica', 'Disf. diastólica')], max_length=44, null=True, verbose_name='FE'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_mets',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ecg', 'ECG'), ('dor', 'Dor'), ('arritmia', 'Arritmia'), ('baixo_pa', '&#8595 PA')], max_length=25, null=True, verbose_name='METs'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_tce',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('da', 'DA'), ('cx', 'CX'), ('cd', 'CD'), ('saf', 'Saf'), ('mam', 'Mam')], max_length=16, null=True, verbose_name='TCE'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='exames_previos_te',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal')], max_length=6, null=True, verbose_name='TE'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hpp_comorbidades',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('avc', 'AVC'), ('irc', 'IRC'), ('aao', 'AAo'), ('doenca_vascular', 'Doença vascular')], max_length=27, null=True, verbose_name='Comorbidades'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hpp_dac',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('iam', 'IAM'), ('crvm', 'CRVM'), ('ptca', 'PTCA'), ('cat_alterado', 'CAT alterado')], max_length=26, null=True, verbose_name='DAC prévia'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hpp_risco',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('has', 'HAS'), ('obesidade', 'Obesidade'), ('dm', 'D.M.'), ('dislipidemia', 'Dislipidemia'), ('tabagismo', 'Tabagismo'), ('hf', 'HF'), ('ex_tabagismo', 'Ex-tabagismo'), ('menopausa', 'Menopausa')], max_length=65, null=True, verbose_name='Fatores de risco'),
        ),
    ]
