# Generated by Django 3.0.8 on 2020-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0009_auto_20201107_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='alergia',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
    ]
