# Generated by Django 3.0.8 on 2020-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0010_auto_20201109_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='tipo_exame',
            field=models.CharField(blank=True, choices=[('Cintilografia Miocárdica', 'Cintilografia Miocárdica'), ('Pesquisa de Viabilidade', 'Pesquisa de Viabilidade')], max_length=255, null=True, verbose_name='Tipo de exame'),
        ),
    ]
